//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerProduct
    {
        public int id_partner_product { get; set; }
        public Nullable<int> id_product { get; set; }
        public Nullable<int> id_partner { get; set; }
        public string count_product { get; set; }
        public Nullable<System.DateTime> date_sale { get; set; }
    
        public virtual Partner Partner { get; set; }
        public virtual Product Product { get; set; }
    }
}
